
@baseUrl = http://localhost:4200
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTA1YTJkYWI3NjEwYjBkNGQ0NjQzM2EiLCJpYXQiOjE3Nzg3NTQyNjZ9._HnqtAgu-8d9vmnSqZCnh73ftcJ-Dd3809pF9Xktoq0
### Get list (Owner)

GET {{baseUrl}}/api/order?page=1&menuId=1
Authorization: {{token}}

### Get list by tableNum (Owner)

GET {{baseUrl}}/api/order?page=1&menuId=1&tableNum=10
Authorization: {{token}}

### Get list by sendTime (Owner)

GET {{baseUrl}}/api/order?page=1&menuId=1&sendTimeStart=2026-05-12T10:48:00Z&sendTimeEnd=2026-05-12T10:49:00Z
Authorization: {{token}}

### Get list by status (Owner)

GET {{baseUrl}}/api/order?page=1&menuId=1&status=new
Authorization: {{token}}

### Get list by finalAmount (Owner)

GET {{baseUrl}}/api/order?page=1&menuId=1&finalAmountMin=2000&finalAmountMax=3000
Authorization: {{token}}

### Create (Client)

POST {{baseUrl}}/api/order
content-type: application/json

{
	"menuId": 1,
	"tableNum": "10",
	"products": [
		{
			"productId" : 5,
			"amount": 2
		},
		{
			"productId" : 2,
			"amount": 2
		}
	]
}

### Update (Client)

POST {{baseUrl}}/api/order
content-type: application/json

{
	"menuId": 1,
	"tableNum": "10",
	"prevAccessKey": "c2d8f895-00fd-47b1-adf7-3f41451079bf",
	"products": [
		{
			"productId" : 5,
			"amount": 2
		},
		{
			"productId" : 2,
			"amount": 2
		}
	]
}

### Cancel (Client)

PATCH {{baseUrl}}/api/order/c2d8f895-00fd-47b1-adf7-3f41451079bf/cancel

### Update status by access keys (Owner)

PATCH {{baseUrl}}/api/order/update/status/by/ids
Authorization: {{token}}
content-type: application/json

{
	"newStatus": "new",
	"ids": [1, 2, 3]
}

### Update status by filters (Owner)

PATCH {{baseUrl}}/api/order/update/status/by/filters
Authorization: {{token}}
content-type: application/json

{
	"newStatus": "banned",
	"menuId": 1
}