@baseUrl = http://localhost:4200
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTBkN2Q4MWE5MTIzM2VkOTYxMDExNzMiLCJpYXQiOjE3NzkyNjg5OTN9.BzXZFXhEUhjhfNZSR4QnGeuHtNHKfRy8we3vqeh8b4I
### Get statistic (Owner)

GET {{baseUrl}}/api/statistic?menuId=1&lastDays=40
Authorization: {{token}}

### Download orders (Owner)

GET {{baseUrl}}/api/statistic/order?menuId=1&lastDays=1
Authorization: {{token}}

### Post statistic (view-menu)

POST {{baseUrl}}/api/statistic
content-type: application/json

{
	"menuId": 5,
    "event": "view-menu",
    "productName": "forgot nulling"
}

### Post statistic (view-product)

POST {{baseUrl}}/api/statistic
content-type: application/json

{
	"menuId": 1,
    "event": "view-product",
    "productName": "Название продукта"
}