### Auth

POST http://localhost:4200/api/user/auth
content-type: application/json

{
  "phone": "+7 (000) 000-00-00",
  "password": "12345678"
}

### Reg

POST http://localhost:4200/api/user/reg
content-type: application/json

{
  "phone": "+7 (000) 000-00-04",
  "email": "example@example.com",
  "name": "  Пользователь 1  ",
  "password": "12345678",
  "avatar": "https://example.com/avatar"
}

### Update

PUT http://localhost:4200/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBkMjU0YjRkOGI1YjhiYTBiNWY3MjEiLCJpYXQiOjE3NDU2OTE5Nzl9.jQQ54oqZ4aG3slVQvPrV-UZXnLclo0rv24Oq4K6Wg38

{
  "phone": "+7 (000) 000-00-09",
  "email": "example@example.com",
  "name": "  Пользователь 1  ",
  "password": "12345678",
  "avatar": "https://example.com/avatar"
}